# Generated by Django 5.0.6 on 2024-06-12 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('object', '0001_initial'),
        ('reviews', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.telegramuser'),
        ),
        migrations.AddField(
            model_name='review',
            name='real_estate',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='object.realty'),
        ),
    ]
