# Generated by Django 5.0.6 on 2024-06-11 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0003_alter_city_time_zone_uts'),
        ('reviews', '0001_initial'),
        ('user', '0003_telegramuser_search_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='real_estate',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='object.realty'),
            preserve_default=False,
        ),
    ]
