# Generated by Django 5.0.6 on 2024-06-11 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_author_review_real_estate'),
        ('user', '0004_telegramuser_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.telegramuser'),
        ),
    ]
