# Generated by Django 5.0.6 on 2024-06-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_author_alter_review_real_estate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('P', 'Ожидает модерации'), ('A', 'Утверждён'), ('R', 'Отклонён')], default='P', max_length=1, verbose_name='Статус'),
        ),
    ]
