volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.15-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
  real_estate:
    build: ./real_estate_service/
    command: python main.py
    env_file: .env
    volumes: 
      - static:/static
      - media:/app/media 
    depends_on:
      - db
      - redis
  celery:
    build: ./real_estate_service/
    command: celery -A real_estate_service worker -l info
    env_file: .env
    depends_on:
      - redis
  celery_beat:
    build: ./real_estate_service/
    command: celery -A real_estate_service beat -l info
    env_file: .env
    depends_on:
      - redis
  gateway:
    build: ./gateway/
    env_file: .env 
    ports:
      - 8000:80 
    volumes: 
      - static:/static
      - media:/media
    depends_on:
      - real_estate