volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.15-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
  real_estate:
    image: meteopavel/premium_product_bot_real_estate
    env_file: .env
    volumes: 
      - static:/static
      - media:/app/media
    depends_on:
      - db
      - redis
  
  gateway:
    image: meteopavel/premium_product_bot_gateway
    env_file: .env 
    ports:
      - 8000:80 
    volumes: 
      - static:/static
      - media:/media
    depends_on:
      - real_estate