# Generated by Django 5.0.6 on 2024-06-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0007_realty_is_active'),
        ('object', '0007_realty_status_realty_type'),
    ]

    operations = [
    ]
