# Generated by Django 5.0.6 on 2024-06-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaIntervals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.PositiveIntegerField(blank=True, null=True, verbose_name='минимальное значение')),
                ('maximum', models.PositiveIntegerField(blank=True, null=True, verbose_name='максимальное значение')),
            ],
            options={
                'verbose_name': 'Интервал площади',
                'verbose_name_plural': 'Интервалы площади',
            },
        ),
        migrations.CreateModel(
            name='PriceIntervals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.PositiveIntegerField(blank=True, null=True, verbose_name='минимальное значение')),
                ('maximum', models.PositiveIntegerField(blank=True, null=True, verbose_name='максимальное значение')),
            ],
            options={
                'verbose_name': 'Интервал цен',
                'verbose_name_plural': 'Интервалы цен',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='is_in_main_menu',
            field=models.BooleanField(default=False, verbose_name='Показать в основном меню'),
        ),
    ]
