# Generated by Django 5.0.6 on 2024-06-05 14:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0002_alter_realty_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.RemoveField(
            model_name='realty',
            name='address',
        ),
        migrations.RemoveField(
            model_name='realty',
            name='city',
        ),
        migrations.RemoveField(
            model_name='realty',
            name='email',
        ),
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='city',
            name='time_zone_uts',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(9)], verbose_name='Временная зона UTS'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='object.country', verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_index', models.CharField(blank=True, max_length=10, null=True, verbose_name='Почтовый индекс')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('building', models.CharField(max_length=30, verbose_name='Строение')),
                ('floor', models.SmallIntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('room', models.CharField(blank=True, max_length=30, null=True, verbose_name='Помещение')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='object.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.AddField(
            model_name='realty',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='object.location', verbose_name='Локация'),
        ),
    ]
