# Generated by Django 5.0.6 on 2024-06-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0003_country_remove_realty_address_remove_realty_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_in_main_menu',
            field=models.BooleanField(default=False, verbose_name='Показать в основном меню'),
        ),
    ]
