# Generated by Django 5.0.6 on 2024-06-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0006_alter_realty_image_workschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
