# Generated by Django 5.0.6 on 2024-06-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaIntervals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.PositiveIntegerField(blank=True, null=True, verbose_name='минимальное значение')),
                ('maximum', models.PositiveIntegerField(blank=True, null=True, verbose_name='максимальное значение')),
            ],
            options={
                'verbose_name': 'Интервал площади',
                'verbose_name_plural': 'Интервалы площади',
            },
        ),
        migrations.CreateModel(
            name='DateInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название периода')),
                ('date_interval', models.SmallIntegerField(verbose_name='количество дней от текущей даты')),
            ],
            options={
                'verbose_name': 'Интервал дней',
                'verbose_name_plural': 'Интервалы дней',
                'ordering': ['date_interval'],
            },
        ),
        migrations.CreateModel(
            name='PriceIntervals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.PositiveIntegerField(blank=True, null=True, verbose_name='минимальное значение')),
                ('maximum', models.PositiveIntegerField(blank=True, null=True, verbose_name='максимальное значение')),
            ],
            options={
                'verbose_name': 'Интервал цен',
                'verbose_name_plural': 'Интервалы цен',
            },
        ),
    ]
