# Generated by Django 5.0.6 on 2024-06-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaintervals',
            name='maximum',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное значение'),
        ),
        migrations.AlterField(
            model_name='areaintervals',
            name='minimum',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальное значение'),
        ),
        migrations.AlterField(
            model_name='priceintervals',
            name='maximum',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное значение'),
        ),
        migrations.AlterField(
            model_name='priceintervals',
            name='minimum',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальное значение'),
        ),
    ]
