# Generated by Django 5.0.6 on 2024-06-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'Администратор', 'verbose_name_plural': 'Администраторы'},
        ),
    ]
