# Generated by Django 5.0.6 on 2024-06-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="is_subscribed",
            field=models.BooleanField(
                default=False, verbose_name="Подписан на обновления"
            ),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="search_parameters",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Строка, хранящая поисковые парамерты",
            ),
        ),
    ]
