# Generated by Django 5.0.6 on 2024-06-15 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_telegramuser_is_subscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='staff_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tg_user', to=settings.AUTH_USER_MODEL, verbose_name='ID сотрудника'),
        ),
    ]
