# Generated by Django 5.0.6 on 2024-06-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_telegramuser_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='search_parameters',
            field=models.TextField(blank=True, null=True, verbose_name='Строка, хранящая поисковые парамерты'),
        ),
    ]
