# Generated by Django 5.0.6 on 2024-06-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_telegramuser_search_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписан на обновления'),
        ),
    ]
