# Generated by Django 5.0.6 on 2024-06-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_telegramuser_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='tg_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram id'),
        ),
    ]
