# Generated by Django 5.0.6 on 2024-06-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_telegramuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
    ]
