# Generated by Django 5.0.6 on 2024-06-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_telegramuser_tg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArhivedTelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True, verbose_name='Telegram id')),
                ('first_name', models.CharField(max_length=150, verbose_name='Telegram first_name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Telegram lastname')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Telegram username')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Registration date')),
                ('search_parameters', models.TextField(blank=True, null=True, verbose_name='Строка, хранящая поисковые парамерты')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='Подписан на обновления')),
                ('reviews', models.TextField(verbose_name='строка, хранящая отзывы пользователя')),
                ('favorites', models.TextField(verbose_name='строка, хранящая избранные обьявления')),
            ],
            options={
                'verbose_name': 'Архивный пользователь Telegram',
                'verbose_name_plural': 'Архивный пользователи Telegram',
                'ordering': ('first_name',),
            },
        ),
    ]
