# Generated by Django 5.0.6 on 2024-06-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_arhivedtelegramuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arhivedtelegramuser',
            options={'verbose_name': 'Архивный пользователь Telegram', 'verbose_name_plural': 'Архивный пользователи Telegram'},
        ),
        migrations.RemoveField(
            model_name='arhivedtelegramuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='arhivedtelegramuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='arhivedtelegramuser',
            name='username',
        ),
        migrations.AddField(
            model_name='arhivedtelegramuser',
            name='arhived_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Arhive date'),
        ),
        migrations.AlterField(
            model_name='arhivedtelegramuser',
            name='created_at',
            field=models.DateTimeField(verbose_name='Registration date'),
        ),
    ]
