# Generated by Django 5.0.6 on 2024-06-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_arhivedtelegramuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arhivedtelegramuser',
            name='favorites',
            field=models.TextField(verbose_name='Строка, хранящая избранные обьявления'),
        ),
        migrations.AlterField(
            model_name='arhivedtelegramuser',
            name='reviews',
            field=models.TextField(verbose_name='Строка, хранящая отзывы пользователя'),
        ),
    ]
