name: Main Premium-product-bot Workflow

on:
  push:
    branches:
      - 10

jobs:
  build_and_push_to_docker_hub:
    name: Push real_estate to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./real_estate_service/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/premium_product_bot_real_estate:latest